Repository commercetools/connect-payment-integration-template, pull requests merged in 2024-06, with the labels that each got.

#240 chore(connector): Inform users on scopes and correct urls
  README.md
  connect.yaml
Labels: 1 min review, missing-jira

#239 chore(connector): improve dev tools
  README.md
  docker-compose.yaml
  enabler/index.html
  processor/package.json
Labels: 5 min review

#236 ci(latest): autoupdate checkout connector
  .github/workflows/ci.yml
  .github/workflows/latest.yml
  .github/workflows/publish.yml
Labels: missing-jira, 5 min review

#248 ci(publish): fix publish repo
  .github/workflows/publish.yml
Labels: missing-jira

#257 chore(all): release-v3.0.4
  enabler/package.json
  processor/package.json
Labels: missing-jira
